from typing import Any, Callable

def urlencode(s: str) -> str: ...

class Request:
    content_type: str | None
    content_length: int
    method: str
    path: str
    url: str
    args: dict[str, str]
    headers: dict[str, str]
    cookies: dict[str, str]

    @property
    def body(self) -> bytes | None: ...
    @property
    def json(self) -> dict[str, Any] | None: ...
    @property
    def form(self) -> dict[str, str] | None: ...

class Microdot:
    def run(self, host: str = ..., port: int = ..., debug: bool = ..., ssl: Any = ...) -> None: ...
    def get(self, url_pattern: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def post(self, url_pattern: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def put(self, url_pattern: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def delete(self, url_pattern: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
